---
- name: Creates state directory
  ansible.builtin.file:
    path: "{{ nixos_rebuild_loc_base }}"
    mode: "0755"
    state: directory
  delegate_to: localhost

- name: Write .gitignore file
  ansible.builtin.template:
    src: templates/ignore.j2
    dest: "{{ nixos_rebuild_loc_base }}/.gitignore"
    mode: "0655"
  delegate_to: localhost

- name: Write variables to file
  ansible.builtin.template:
    src: templates/json.j2
    dest: "{{ nixos_rebuild_loc_json }}"
    mode: "0655"
  delegate_to: localhost
  no_log: true

- name: Write deploy script to file
  ansible.builtin.template:
    src: templates/script.j2
    dest: "{{ nixos_rebuild_loc_script }}"
    mode: "0755"
  delegate_to: localhost

- name: Setup flake url
  block:
    - name: Deploy "{{ nixos_rebuild_flake_url }}"
      ansible.builtin.shell: |
        if ! [ -z "$NIXOS_SILENT" [; then
          exec \
            1> >(tee >(awk '{ system(""); print "[{{ nixos_rebuild_flake_target }}] stdout:", $0; system(""); }' >> /dev/tty)) \
            2> >(tee >(awk '{ system(""); print "[{{ nixos_rebuild_flake_target }}] stderr:", $0; system(""); }' >> /dev/tty) >&2)
        fi

        {{ nixos_rebuild_loc_script }}
      delegate_to: localhost
      changed_when: false
      register: _nixos_rebuild
      when: not ansible_check_mode

    - name: Gather host facts again
      ansible.builtin.setup:
  rescue:
    - name: >
        NixOS Deployment failed:
        {{ _nixos_rebuild.stderr }}
      ansible.builtin.fail:
        msg: "NixOS Deployment failed for {{ nixos_rebuild_flake_url }}"
      delegate_to: localhost
