---
- name: Check if nix is installed
  ansible.builtin.stat:
    path: /nix/store
  register: _nix_store

- name: Install curl and xz-utils
  ansible.builtin.package:
    name:
      - curl
      - xz-utils
    state: present
  when: not _nix_store.stat.exists

- name: Install nix
  ansible.builtin.shell: |
    set -o pipefail && yes y | sh <(curl -L https://nixos.org/nix/install) --daemon
    for f in /nix/var/nix/profiles/default/bin/nix*; do
      ln -s "$f" "/usr/bin/$(basename "$f")"
    done
  args:
    executable: /bin/bash
  changed_when: false
  when: _not nix_store.stat.exists
